---
- name: Add EPEL repo
  yum: name=epel-release state=installed

- name: Install Redis
  yum: name=redis state=present

- name: Start and enable redis service
  service: name=redis state=started enabled=yes
