---
- name: Add nginx repo
  yum_repository:
    name: nginx
    description: nginx
    baseurl: http://nginx.org/packages/mainline/centos/7/$basearch
    gpgkey: http://nginx.org/keys/nginx_signing.key
    gpgcheck: yes
    enabled: yes

- name: Install Nginx
  yum: name=nginx state=present

- name: Create ssl directory for Nginx
  file: path=/etc/nginx/ssl state=directory

- name: Generate self-signed certificate
  command: openssl req -new -x509 -nodes -days 3560 -out own.crt -keyout own.key -subj "/C=US/ST=New York"
  args:
    chdir: /etc/nginx/ssl
    creates: /etc/nginx/ssl/own.crt

- name: Generate unique Diffie-Hellman group
  command: openssl dhparam -out dhparams.pem 2048
  args:
    chdir: /etc/nginx
    creates: /etc/nginx/dhparams.pem

- name: Replace Nginx configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: reload nginx

- name: Replace Nginx default virtual host
  template: src=conf.d/default.conf dest=/etc/nginx/conf.d/default.conf
  notify: reload nginx

- name: Add Nginx example virtual host
  template: src=conf.d/example.com dest=/etc/nginx/conf.d/example.com
  notify: reload nginx

- name: Add Nginx phpMyAdmin virtual host
  template: src=conf.d/phpmyadmin dest=/etc/nginx/conf.d/phpmyadmin
  notify: reload nginx

- name: Add Nginx common.conf
  template: src=common.conf dest=/etc/nginx/common.conf
  notify: reload nginx

- name: Add Nginx try.conf
  template: src=try.conf dest=/etc/nginx/try.conf
  notify: reload nginx

- name: Add Nginx php-fpm.conf
  template: src=php-fpm.conf dest=/etc/nginx/php-fpm.conf
  notify: reload nginx

- name: Add Nginx magento.conf
  template: src=magento.conf dest=/etc/nginx/magento.conf
  notify: reload nginx

- name: Add CloudFlare IPs (v4) for Nginx
  shell: curl -s https://www.cloudflare.com/ips-v4 | sed -r 's/^(.+)$/set_real_ip_from \1;/g' > /etc/nginx/cloudflare.conf
  changed_when: false

- name: Add CloudFlare IPs (v6) for Nginx
  shell: curl -s https://www.cloudflare.com/ips-v6 | sed -r 's/^(.+)$/set_real_ip_from \1;/g' >> /etc/nginx/cloudflare.conf
  changed_when: false

- name: Open port 80 (HTTP)
  firewalld: port=80/tcp permanent=true state=enabled immediate=yes

- name: Open port 443 (HTTPS)
  firewalld: port=443/tcp permanent=true state=enabled immediate=yes

- name: Open port 8001 (phpMyAdmin)
  firewalld: port=8001/tcp permanent=true state=enabled immediate=yes

- name: Start and enable Nginx service
  service: name=nginx state=started enabled=yes
