---
- name: Add nginx repo
  yum_repository:
    name: nginx
    description: nginx
    baseurl: http://nginx.org/packages/centos/7/$basearch
    gpgkey: http://nginx.org/keys/nginx_signing.key
    gpgcheck: yes
    enabled: yes

- name: Install Nginx
  yum: name=nginx state=present

- name: Create ssl directory for Nginx
  file: path=/etc/nginx/ssl state=directory

- name: Generate self-signed certificate
  command: openssl req -new -x509 -nodes -days 3560 -out own.crt -keyout own.key -subj "/C=US/ST=New York"
  args:
    chdir: /etc/nginx/ssl
    creates: /etc/nginx/ssl/own.crt

- name: Generate unique Diffie-Hellman group
  command: openssl dhparam -out dhparams.pem 2048
  args:
    chdir: /etc/nginx
    creates: /etc/nginx/dhparams.pem
  notify: reload nginx

- name: Replace Nginx configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: reload nginx

- name: Open port 80
  firewalld: port=80/tcp permanent=true state=enabled immediate=yes

- name: Open port 443
  firewalld: port=443/tcp permanent=true state=enabled immediate=yes

- name: Start and enable Nginx service
  service: name=nginx state=started enabled=yes
