---
- name: Install LEMP on CentOS 7
  user: root
  hosts: local

  roles:
    - common
    - update
    - auto-updates
    - swap
    - sysctl
    - ntp
    - mariadb
    - nginx
    - php-global
    - php-additional
    - nodejs
    - redis
    - certbot
    - pure-ftpd
