---
- name: Install LEMP on CentOS 7
  user: root
  hosts: local

  roles:
  # general
    - common
    - update
    - auto-updates
    - swap
    - sysctl
    - chrony

  # web server
    - mariadb
    - nginx
    - php-global
    - php-additional
    - phpmyadmin
    # - hhvm
    - pure-ftpd

  # backups
    - rsnapshot

  # extras
    - nodejs
    - redis
    - certbot
