---
- name: Add mariadb repo
  yum_repository:
    name: mariadb
    description: mariadb
    baseurl: http://yum.mariadb.org/{{ mariadb_ver }}/centos7-amd64
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: 1
    enabled: 1

- name: Install MariaDB packages
  yum: name={{ item }} state=installed
  with_items:
    - MariaDB-server
    - MariaDB-client
    - MySQL-python

- name: Create MariaDB log directory
  file: path=/var/log/mariadb state=directory owner=mysql group=mysql mode=0755

- name: Replace MariaDB configuration file
  template: src=server.cnf dest=/etc/my.cnf.d/server.cnf
  notify:
    - restart mariadb

- name: Start and enable MariaDB Service
  service: name=mariadb state=started enabled=yes

- name: Remove MariaDB anonymous user
  mysql_user: name='' host_all=yes state=absent

- name: Remove MariaDB test db
  mysql_db: name=test state=absent

- name: Disallow MariaDB remote root login
  command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false

- name: Set MariaDB root password
  mysql_user:
    name=root
    password="{{ lookup('password', '/root/credentials/mysql') }}"
    host={{item}}
    state=present
  with_items:
    - '::1'
    - '127.0.0.1'
    - 'localhost'

- name: Create .my.cnf with MariaDB root credentials
  template: src=.my.cnf dest=/root/.my.cnf mode=0600
