---
- name: Install MariaDB packages
  yum: name={{ item }} state=installed
  with_items:
   - MariaDB-server
   - MariaDB-client

- name: Replace MariaDB configuration file
  template: src=server.cnf dest=/etc/my.cnf.d/server.cnf
  notify:
  - restart mariadb

- name: Create MariaDB log directory
  file: path=/var/log/mariadb state=directory owner=mysql group=mysql mode=0775

- name: Remove MariaDB anonymous users
  mysql_user: name='' host_all=yes state=absent

- name: Remove MariaDB test db
	mysql_db: name=test state=absent

- name: Set MariaDB root password
  mysql_user: name=root password={{ mysql_root_pass }} host_all=yes state=present

- name: Create .my.cnf with MariaDB root credentials
  template: src=.my.cnf dest=/root/.my.cnf owner=root mode=0600

- name: Add MariaDB app user
  mysql_user: name={{ mysql_app_user }} password={{ mysql_app_user_pass }} priv=*.*:ALL,GRANT state=present

- name: Start and enable MariaDB Service
  service: name=mariadb state=started enabled=yes
