---
- name: Add remi repo
  yum_repository:
    name: remi
    description: remi
    mirrorlist: http://rpms.remirepo.net/enterprise/7/remi/mirror
    gpgkey: http://rpms.remirepo.net/RPM-GPG-KEY-remi
    gpgcheck: yes
    enabled: yes

- name: Add remi-safe repo
  yum_repository:
    name: remi-safe
    description: remi-safe
    mirrorlist: http://rpms.remirepo.net/enterprise/7/safe/mirror
    gpgkey: http://rpms.remirepo.net/RPM-GPG-KEY-remi
    gpgcheck: yes
    enabled: yes

- name: Install PHP {{ php_ver_additional }}
  yum: name={{ item }} state=present
  with_items:
    - "php{{ php_ver_additional | replace('.', '') }}-php-cli"
    - "php{{ php_ver_additional | replace('.', '') }}-php-curl"
    - "php{{ php_ver_additional | replace('.', '') }}-php-fpm"
    - "php{{ php_ver_additional | replace('.', '') }}-php-gd"
    - "php{{ php_ver_additional | replace('.', '') }}-php-intl"
    - "php{{ php_ver_additional | replace('.', '') }}-php-mbstring"
    - "php{{ php_ver_additional | replace('.', '') }}-php-mcrypt"
    - "php{{ php_ver_additional | replace('.', '') }}-php-memcached"
    - "php{{ php_ver_additional | replace('.', '') }}-php-mysqlnd"
    - "php{{ php_ver_additional | replace('.', '') }}-php-opcache"
    - "php{{ php_ver_additional | replace('.', '') }}-php-pdo"
    - "php{{ php_ver_additional | replace('.', '') }}-php-pear"
    - "php{{ php_ver_additional | replace('.', '') }}-php-pear"
    - "php{{ php_ver_additional | replace('.', '') }}-php-pecl-redis"
    - "php{{ php_ver_additional | replace('.', '') }}-php-pecl-zip"
    - "php{{ php_ver_additional | replace('.', '') }}-php-soap"
    - "php{{ php_ver_additional | replace('.', '') }}-php-xml"

- name: Replace PHP {{ php_ver_additional }} FPM pool configuration
  template: src=www.conf dest=/etc/opt/remi/php{{ php_ver_additional | replace('.', '') }}/php-fpm.d/www.conf
  notify: restart php-fpm-additional

- name: Replace PHP {{ php_ver_additional }} php.ini configuration
  template: src=php.ini dest=/etc/opt/remi/php{{ php_ver_additional | replace('.', '') }}/php.ini
  notify: restart php-fpm-additional

- name: Start and enable PHP {{ php_ver_additional }} FPM service
  service: name=php{{ php_ver_additional | replace('.', '') }}-php-fpm state=started enabled=yes

- include: ioncube.yml
  when: php_install_ioncube
