# Increase size of file handles and inode cache
- sysctl: fs.file-max value=2097152

# Do less swapping
- sysctl: vm.swappiness value=1
- sysctl: vm.dirty_ratio value=60
- sysctl: vm.dirty_background_ratio value=2

# Number of times SYNACKs for passive TCP connection.
- sysctl: net.ipv4.tcp_synack_retries value=2

# Allowed local port range
- sysctl: net.ipv4.ip_local_port_range value="2000 65535"

# Protect Against TCP Time-Wait
- sysctl: net.ipv4.tcp_rfc1337 value=1

# Decrease the time default value for tcp_fin_timeout connection
- sysctl: net.ipv4.tcp_fin_timeout value=3

# Decrease the time default value for connections to keep alive
- sysctl: net.ipv4.tcp_keepalive_time value=300
- sysctl: net.ipv4.tcp_keepalive_probes value=5
- sysctl: net.ipv4.tcp_keepalive_intvl value=15

# Default Socket Receive Buffer
- sysctl: net.core.rmem_default value=31457280

# Maximum Socket Receive Buffer
- sysctl: net.core.rmem_max value=12582912

# Default Socket Send Buffer
- sysctl: net.core.wmem_default value=31457280

# Maximum Socket Send Buffer
- sysctl: net.core.wmem_max value=12582912

# Increase number of incoming connections
- sysctl: net.core.somaxconn value=32768

# Increase number of incoming connections backlog
- sysctl: net.core.netdev_max_backlog value=262144

# Increase the maximum amount of option memory buffers
- sysctl: net.core.optmem_max value=25165824

# Increase the maximum total buffer-space allocatable
# This is measured in units of pages (4096 bytes)
- sysctl: net.ipv4.tcp_mem value="65536 131072 262144"
- sysctl: net.ipv4.udp_mem value="65536 131072 262144"

# Increase the read-buffer space allocatable
- sysctl: net.ipv4.tcp_rmem value="8192 87380 16777216"
- sysctl: net.ipv4.udp_rmem_min value=16384

# Increase the write-buffer-space allocatable
- sysctl: net.ipv4.tcp_wmem value="8192 65536 16777216"
- sysctl: net.ipv4.udp_wmem_min value=16384

# Increase the tcp-time-wait buckets pool size to prevent simple DOS attacks
- sysctl: net.ipv4.tcp_max_tw_buckets value=1440000
- sysctl: net.ipv4.tcp_tw_recycle value=0
- sysctl: net.ipv4.tcp_tw_reuse value=1

# Increase the inotify watches limit
- sysctl: fs.inotify.max_user_watches value=100000
