# https://easyengine.io/tutorials/linux/sysctl-conf/
# https://gist.github.com/dctrwatson/0b3b52050254e273ff11

- name: fs.file-max
  sysctl: name=fs.file-max value=2097152

- name: vm.swappiness
  sysctl: name=vm.swappiness value=1

- name: vm.dirty_ratio
  sysctl: name=vm.dirty_ratio value=60

- name: vm.dirty_background_ratio
  sysctl: name=vm.dirty_background_ratio value=2

- name: net.ipv4.tcp_synack_retries
  sysctl: name=net.ipv4.tcp_synack_retries value=2

- name: net.ipv4.ip_local_port_range
  sysctl: name=net.ipv4.ip_local_port_range value="2000 65535"

- name: net.ipv4.tcp_rfc1337
  sysctl: name=net.ipv4.tcp_rfc1337 value=1

- name: net.ipv4.tcp_fin_timeout
  sysctl: name=net.ipv4.tcp_fin_timeout value=3

- name: net.ipv4.tcp_keepalive_time
  sysctl: name=net.ipv4.tcp_keepalive_time value=300

- name: net.ipv4.tcp_keepalive_probes
  sysctl: name=net.ipv4.tcp_keepalive_probes value=5

- name: net.ipv4.tcp_keepalive_intvl
  sysctl: name=net.ipv4.tcp_keepalive_intvl value=15

- name: net.core.rmem_default
  sysctl: name=net.core.rmem_default value=31457280

- name: net.core.rmem_max
  sysctl: name=net.core.rmem_max value=12582912

- name: net.core.wmem_default
  sysctl: name=net.core.wmem_default value=31457280

- name: net.core.wmem_max
  sysctl: name=net.core.wmem_max value=12582912

- name: net.core.somaxconn
  sysctl: name=net.core.somaxconn value=32768

- name: net.core.netdev_max_backlog
  sysctl: name=net.core.netdev_max_backlog value=262144

- name: net.core.optmem_max
  sysctl: name=net.core.optmem_max value=25165824

- name: net.ipv4.tcp_mem
  sysctl: name=net.ipv4.tcp_mem value="65536 131072 262144"

- name: net.ipv4.udp_mem
  sysctl: name=net.ipv4.udp_mem value="65536 131072 262144"

- name: net.ipv4.tcp_rmem
  sysctl: name=net.ipv4.tcp_rmem value="8192 87380 16777216"

- name: net.ipv4.udp_rmem_min
  sysctl: name=net.ipv4.udp_rmem_min value=16384

- name: net.ipv4.tcp_wmem
  sysctl: name=net.ipv4.tcp_wmem value="8192 65536 16777216"

- name: net.ipv4.udp_wmem_min
  sysctl: name=net.ipv4.udp_wmem_min value=16384

- name: net.ipv4.tcp_max_tw_buckets
  sysctl: name=net.ipv4.tcp_max_tw_buckets value=1440000

- name: net.ipv4.tcp_tw_recycle
  sysctl: name=net.ipv4.tcp_tw_recycle value=0

- name: net.ipv4.tcp_tw_reuse
  sysctl: name=net.ipv4.tcp_tw_reuse value=1

- name: fs.inotify.max_user_watches
  sysctl: name=fs.inotify.max_user_watches value=100000
