---
# Timezone

- name: Set server timezone
  command: timedatectl set-timezone {{ timezone }}
  changed_when: false

# Hostname

- name: Set server hostname
  command: hostnamectl set-hostname {{ hostname }}
  changed_when: false

# App user

- name: Add app user
  user: name={{ app_user }} state=present

- name: Set app user home directory permissions
  file: path=/home/{{ app_user }} state=directory owner={{ app_user }} group={{ app_user }} mode=0755

## Basic packages

- name: Install basic packages
  yum: name={{ item }} state=present
  with_items:
    - nano
    - wget
    - net-tools
    - git
    - bzip2
    - unzip

# FirewallD

- name: Install FirewallD
  yum: name=firewalld state=present

- name: Start and enable firewalld service
  service: name=firewalld state=started enabled=yes

# SELinux

- name: Disable SELinux
  selinux: state=disabled
  changed_when: false
  # check if permanent
