---
- name: Add app user
  user: name={{ app_user }} state=present

- name: Set app user home directory permissions
  file: path=/home/{{ app_user }} state=directory owner={{ app_user }} group={{ app_user }} mode=0755

# EPEL

- name: Add EPEL repo
  yum: name=epel-release state=installed

## Basic packages

- name: Install basic packages
  yum: name={{ item }} state=present
  with_items:
    - nano
    - wget
    - net-tools
    - git
    - bzip2
    - unzip
    - pwgen

# FirewallD

- name: Install FirewallD
  yum: name=firewalld state=present

- name: Start and enable firewalld service
  service: name=firewalld state=started enabled=yes

# SELinux

- name: Disable SELinux
  selinux: state=disabled
