---
- name: Download ionCube Loader for PHP {{ php_ver_global }}
  get_url:
    url=http://downloads3.ioncube.com/loader_downloads/ioncube_loaders_lin_x86-64_5.1.2.tar.gz
    dest=/tmp/ioncube-{{ php_ver_global }}.tar.gz
  when: php_ver_global != "7.0"

- name: Download ionCube Loader for PHP {{ php_ver_global }}
  get_url:
    url=https://www.ioncube.com/php7-linux-x86-64-beta8.tgz
    dest=/tmp/ioncube-{{ php_ver_global }}.tar.gz
  when: php_ver_global == "7.0"

- name: Extract ionCube Loader for PHP {{ php_ver_global }}
  unarchive:
    src=/tmp/ioncube-{{ php_ver_global }}.tar.gz
    dest=/tmp
    copy=no
  when: php_install_ioncube

- name: Install ionCube Loader for PHP {{ php_ver_global }}
  copy:
    src=/tmp/ioncube/ioncube_loader_lin_{{ php_ver_global }}.so
    dest=/usr/lib64/php/modules
  when: php_ver_global != "7.0"
  notify: restart php-fpm

- name: Install ionCube Loader for PHP {{ php_ver_global }}
  copy:
    src=/tmp/ioncube_loader_lin_x86-64_{{ php_ver_global }}b8.so
    dest=/usr/lib64/php/modules/ioncube_loader_lin_{{ php_ver_global }}.so
  when: php_ver_global == "7.0"
  notify: restart php-fpm

- name: Enable ionCube Loader for PHP {{ php_ver_global }}
  template: src=ioncube.ini dest=/etc/php.d/00-ioncube.ini
  notify: restart php-fpm
