---
- name: Add remi repo
  yum_repository:
    name: remi
    description: remi
    mirrorlist: http://rpms.remirepo.net/enterprise/7/remi/mirror
    gpgkey: http://rpms.remirepo.net/RPM-GPG-KEY-remi
    gpgcheck: yes
    enabled: yes

- name: Add remi-php{{ php_ver_global | replace('.', '') }} repo
  yum_repository:
    name: remi-php{{ php_ver_global | replace('.', '') }}
    description: remi-php{{ php_ver_global | replace('.', '') }}
    mirrorlist: http://rpms.remirepo.net/enterprise/7/php{{ php_ver_global | replace('.', '') }}/mirror
    gpgkey: http://rpms.remirepo.net/RPM-GPG-KEY-remi
    gpgcheck: yes
    enabled: yes

- name: Install PHP {{ php_ver_global }}
  yum: name={{ item }} state=present
  with_items:
    - composer
    - php-cli
    - php-curl
    - php-fpm
    - php-gd
    - php-intl
    - php-mbstring
    - php-mcrypt
    - php-memcached
    - php-mysqlnd
    - php-opcache
    - php-pdo
    - php-pear
    - php-pecl-redis
    - php-pecl-zip
    - php-soap
    - php-xml

- name: Replace PHP {{ php_ver_global }} FPM pool configuration
  template: src=www.conf dest=/etc/php-fpm.d/
  notify: restart php-fpm

- name: Replace PHP {{ php_ver_global }} php.ini configuration
  template: src=php.ini dest=/etc/
  notify: restart php-fpm

- name: Start and enable PHP {{ php_ver_global }} FPM service
  service: name=php-fpm state=started enabled=yes

- include: ioncube.yml
  when: php_install_ioncube
